package com.form3.payment.model;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * todo add comments.
 * <p>
 * Generated by http://www.jsonschema2pojo.org/
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "amount",
        "beneficiary_party",
        "charges_information",
        "currency",
        "debtor_party",
        "end_to_end_reference",
        "fx",
        "numeric_reference",
        "payment_id",
        "payment_purpose",
        "payment_scheme",
        "payment_type",
        "processing_date",
        "reference",
        "scheme_payment_sub_type",
        "scheme_payment_type",
        "sponsor_party"
})
public class Attributes {

    @JsonProperty("amount")
    private String amount;

    @JsonProperty("beneficiary_party")
    private BeneficiaryParty beneficiaryParty;

    @JsonProperty("charges_information")
    private ChargesInformation chargesInformation;

    @JsonProperty("currency")
    private String currency;

    @JsonProperty("debtor_party")
    private DebtorParty debtorParty;

    @JsonProperty("end_to_end_reference")
    private String endToEndReference;

    @JsonProperty("fx")
    private Fx fx;

    @JsonProperty("numeric_reference")
    private String numericReference;

    @JsonProperty("payment_id")
    private String paymentId;

    @JsonProperty("payment_purpose")
    private String paymentPurpose;

    @JsonProperty("payment_scheme")
    private String paymentScheme;

    @JsonProperty("payment_type")
    private String paymentType;

    @JsonProperty("processing_date")
    private String processingDate;

    @JsonProperty("reference")
    private String reference;

    @JsonProperty("scheme_payment_sub_type")
    private String schemePaymentSubType;

    @JsonProperty("scheme_payment_type")
    private String schemePaymentType;

    @JsonProperty("sponsor_party")
    private SponsorParty sponsorParty;

    @JsonIgnore
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("amount")
    public String getAmount() {
        return amount;
    }

    @JsonProperty("amount")
    public void setAmount(String amount) {
        this.amount = amount;
    }

    @JsonProperty("beneficiary_party")
    public BeneficiaryParty getBeneficiaryParty() {
        return beneficiaryParty;
    }

    @JsonProperty("beneficiary_party")
    public void setBeneficiaryParty(BeneficiaryParty beneficiaryParty) {
        this.beneficiaryParty = beneficiaryParty;
    }

    @JsonProperty("charges_information")
    public ChargesInformation getChargesInformation() {
        return chargesInformation;
    }

    @JsonProperty("charges_information")
    public void setChargesInformation(ChargesInformation chargesInformation) {
        this.chargesInformation = chargesInformation;
    }

    @JsonProperty("currency")
    public String getCurrency() {
        return currency;
    }

    @JsonProperty("currency")
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    @JsonProperty("debtor_party")
    public DebtorParty getDebtorParty() {
        return debtorParty;
    }

    @JsonProperty("debtor_party")
    public void setDebtorParty(DebtorParty debtorParty) {
        this.debtorParty = debtorParty;
    }

    @JsonProperty("end_to_end_reference")
    public String getEndToEndReference() {
        return endToEndReference;
    }

    @JsonProperty("end_to_end_reference")
    public void setEndToEndReference(String endToEndReference) {
        this.endToEndReference = endToEndReference;
    }

    @JsonProperty("fx")
    public Fx getFx() {
        return fx;
    }

    @JsonProperty("fx")
    public void setFx(Fx fx) {
        this.fx = fx;
    }

    @JsonProperty("numeric_reference")
    public String getNumericReference() {
        return numericReference;
    }

    @JsonProperty("numeric_reference")
    public void setNumericReference(String numericReference) {
        this.numericReference = numericReference;
    }

    @JsonProperty("payment_id")
    public String getPaymentId() {
        return paymentId;
    }

    @JsonProperty("payment_id")
    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId;
    }

    @JsonProperty("payment_purpose")
    public String getPaymentPurpose() {
        return paymentPurpose;
    }

    @JsonProperty("payment_purpose")
    public void setPaymentPurpose(String paymentPurpose) {
        this.paymentPurpose = paymentPurpose;
    }

    @JsonProperty("payment_scheme")
    public String getPaymentScheme() {
        return paymentScheme;
    }

    @JsonProperty("payment_scheme")
    public void setPaymentScheme(String paymentScheme) {
        this.paymentScheme = paymentScheme;
    }

    @JsonProperty("payment_type")
    public String getPaymentType() {
        return paymentType;
    }

    @JsonProperty("payment_type")
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    @JsonProperty("processing_date")
    public String getProcessingDate() {
        return processingDate;
    }

    @JsonProperty("processing_date")
    public void setProcessingDate(String processingDate) {
        this.processingDate = processingDate;
    }

    @JsonProperty("reference")
    public String getReference() {
        return reference;
    }

    @JsonProperty("reference")
    public void setReference(String reference) {
        this.reference = reference;
    }

    @JsonProperty("scheme_payment_sub_type")
    public String getSchemePaymentSubType() {
        return schemePaymentSubType;
    }

    @JsonProperty("scheme_payment_sub_type")
    public void setSchemePaymentSubType(String schemePaymentSubType) {
        this.schemePaymentSubType = schemePaymentSubType;
    }

    @JsonProperty("scheme_payment_type")
    public String getSchemePaymentType() {
        return schemePaymentType;
    }

    @JsonProperty("scheme_payment_type")
    public void setSchemePaymentType(String schemePaymentType) {
        this.schemePaymentType = schemePaymentType;
    }

    @JsonProperty("sponsor_party")
    public SponsorParty getSponsorParty() {
        return sponsorParty;
    }

    @JsonProperty("sponsor_party")
    public void setSponsorParty(SponsorParty sponsorParty) {
        this.sponsorParty = sponsorParty;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

}
