package com.form3.payment.model;

import java.util.UUID;

import com.couchbase.client.java.repository.annotation.Id;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "id",
        "type",
        "version",
        "organisation_id",
        "attributes"
})
/**
 * todo add comments.
 * <p>
 * Generated by http://www.jsonschema2pojo.org/
 */
public class Payment {

    @JsonProperty("id")
    @Id
    private UUID id;

    @JsonProperty("type")
    private String type;

    @JsonProperty("version")
    private int version;

    @JsonProperty("organisation_id")
    private String organisationId;

    @JsonProperty("attributes")
    private Attributes attributes;

    @Override
    public boolean equals(final Object o) {
        if (this == o)
            return true;
        if (!(o instanceof Payment))
            return false;

        final Payment payment = (Payment) o;

        if (getVersion() != payment.getVersion())
            return false;
        if (getId() != null ? !getId().equals(payment.getId()) : payment.getId() != null)
            return false;
        if (getType() != null ? !getType().equals(payment.getType()) : payment.getType() != null)
            return false;
        if (getOrganisationId() != null ? !getOrganisationId().equals(payment.getOrganisationId()) : payment.getOrganisationId() != null)
            return false;
        return getAttributes() != null ? getAttributes().equals(payment.getAttributes()) : payment.getAttributes() == null;
    }

    @Override
    public int hashCode() {
        int result = getId() != null ? getId().hashCode() : 0;
        result = 31 * result + (getType() != null ? getType().hashCode() : 0);
        result = 31 * result + getVersion();
        result = 31 * result + (getOrganisationId() != null ? getOrganisationId().hashCode() : 0);
        result = 31 * result + (getAttributes() != null ? getAttributes().hashCode() : 0);
        return result;
    }

    @JsonProperty("id")
    public UUID getId() {
        return id;
    }

    @JsonProperty("id")
    public void setId(UUID id) {
        this.id = id;
    }

    @JsonProperty("type")
    public String getType() {
        return type;
    }

    @JsonProperty("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonProperty("version")
    public int getVersion() {
        return version;
    }

    @JsonProperty("version")
    public void setVersion(int version) {
        this.version = version;
    }

    @JsonProperty("organisation_id")
    public String getOrganisationId() {
        return organisationId;
    }

    @JsonProperty("organisation_id")
    public void setOrganisationId(String organisationId) {
        this.organisationId = organisationId;
    }

    @JsonProperty("attributes")
    public Attributes getAttributes() {
        return attributes;
    }

    @JsonProperty("attributes")
    public void setAttributes(Attributes attributes) {
        this.attributes = attributes;
    }
}
