package com.form3.payment.model;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import com.couchbase.client.java.repository.annotation.Id;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "id",
        "type",
        "version",
        "organisation_id",
        "attributes"
})
/**
 * todo add comments.
 * <p>
 * Generated by http://www.jsonschema2pojo.org/
 */
public class Payment {

    @JsonProperty("id")
    @Id
    private UUID id;

    @JsonProperty("type")
    private String type;

    @JsonProperty("version")
    private int version;

    @JsonProperty("organisation_id")
    private String organisationId;

    @JsonProperty("attributes")
    private Attributes attributes;

    @JsonIgnore
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("id")
    public UUID getId() {
        return id;
    }

    @JsonProperty("id")
    public void setId(UUID id) {
        this.id = id;
    }

    @JsonProperty("type")
    public String getType() {
        return type;
    }

    @JsonProperty("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonProperty("version")
    public int getVersion() {
        return version;
    }

    @JsonProperty("version")
    public void setVersion(int version) {
        this.version = version;
    }

    @JsonProperty("organisation_id")
    public String getOrganisationId() {
        return organisationId;
    }

    @JsonProperty("organisation_id")
    public void setOrganisationId(String organisationId) {
        this.organisationId = organisationId;
    }

    @JsonProperty("attributes")
    public Attributes getAttributes() {
        return attributes;
    }

    @JsonProperty("attributes")
    public void setAttributes(Attributes attributes) {
        this.attributes = attributes;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

}
